#!/usr/bin/env -S node
import type { Contract as End } from '../../snapshots/313afba434db8f2796e5d1e2c8134c9ee930b3206447d9db4c4e82a4e866616e/contract';
import endContract from '../../snapshots/313afba434db8f2796e5d1e2c8134c9ee930b3206447d9db4c4e82a4e866616e/contract.json' with { type: 'json' };
import {
  Migration,
  MigrationCLI,
  checkExpression,
  col,
  fn,
  lit,
  primaryKey,
} from '@prisma/orm-postgres/migration';

export default class M extends Migration<never, End> {
  override readonly endContractJson = endContract;

  override get operations() {
    return [
      this.createSchema({ schema: 'public' }),
      this.createTable({
        schema: 'public',
        table: 'ai_summary',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('generatedAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('highlights', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('modelVersion', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('productId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('sentimentScore', 'float8', { codecRef: { codecId: 'pg/float8@1' } }),
          col('shopId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('summaryText', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'customer',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('email', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('firstName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('lastName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('shopId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('shopifyCustomerId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'order',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('customerId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('deliveredAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('email', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('fulfilledAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('fulfillmentStatus', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('shopId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('shopifyOrderId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('shopifyOrderNumber', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'order_line_item',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('orderId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('productId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('quantity', 'int4', {
            notNull: true,
            default: lit(1),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('shopifyLineItemId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('sku', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('title', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'product',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('handle', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('imageUrl', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('shopId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('shopifyProductId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('active'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('title', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'product_status_check_c6c4366c',
            "\"status\" IN ('active', 'archived', 'draft')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'review',
        columns: [
          col('body', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('customerId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('isVerifiedPurchase', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('merchantRepliedAt', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('merchantReply', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('orderId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('orderLineItemId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('productId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('publishedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('rating', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('reviewerEmail', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('reviewerName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('shopId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('source', 'text', {
            notNull: true,
            default: lit('native'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('status', 'text', {
            notNull: true,
            default: lit('pending'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('title', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'review_source_check_f8bcd829',
            "\"source\" IN ('native', 'import', 'email_request', 'widget', 'api')",
          ),
          checkExpression(
            'review_status_check_217a058e',
            "\"status\" IN ('pending', 'approved', 'rejected', 'spam', 'published')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'review_media',
        columns: [
          col('altText', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('reviewId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('sortOrder', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('thumbnailUrl', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('url', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression('review_media_type_check_382e0f81', "\"type\" IN ('image', 'video')"),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'review_reply',
        columns: [
          col('authorName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('body', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('publishedAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('reviewId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('userId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'review_request',
        columns: [
          col('completedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('customerId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('email', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('expiresAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('openedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('orderId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('orderLineItemId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('productId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('scheduledAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('sentAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('shopId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('pending'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('token', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'review_request_status_check_a0dfc826',
            "\"status\" IN ('pending', 'sent', 'opened', 'completed', 'expired', 'cancelled')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'shop',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('currency', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('email', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('installedAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('name', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('shopifyDomain', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('shopifyShopId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('timezone', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('uninstalledAt', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'shop_settings',
        columns: [
          col('autoPublishReviews', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('branding', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('emailEnabled', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('minRatingToPublish', 'int4', {
            notNull: true,
            default: lit(4),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('requestDelayDays', 'int4', {
            notNull: true,
            default: lit(7),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('shopId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('widgetEnabled', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'shopify_session',
        columns: [
          col('accessToken', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('expiresAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('isOnline', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('scope', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('sessionId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('shopId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('state', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'sync_job',
        columns: [
          col('completedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('errorMessage', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('payload', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('shopId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('startedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('pending'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'sync_job_status_check_99149439',
            "\"status\" IN ('pending', 'running', 'completed', 'failed')",
          ),
          checkExpression(
            'sync_job_type_check_e3bcbce0',
            "\"type\" IN ('products', 'orders', 'customers', 'reviews_import', 'full_sync')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'user',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('email', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('firstName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('lastName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('role', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('shopId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('shopifyUserId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'webhook_event',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('errorMessage', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('payload', 'json', { notNull: true, codecRef: { codecId: 'pg/json@1' } }),
          col('processedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('shopId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('shopifyWebhookId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('pending'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('topic', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'webhook_event_status_check_29e2c2cd',
            "\"status\" IN ('pending', 'processed', 'failed')",
          ),
        ],
      }),
      this.addUnique({
        schema: 'public',
        table: 'ai_summary',
        constraint: 'ai_summary_shopId_productId_key',
        columns: ['shopId', 'productId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'customer',
        constraint: 'customer_shopId_shopifyCustomerId_key',
        columns: ['shopId', 'shopifyCustomerId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'order',
        constraint: 'order_shopId_shopifyOrderId_key',
        columns: ['shopId', 'shopifyOrderId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'order_line_item',
        constraint: 'order_line_item_orderId_shopifyLineItemId_key',
        columns: ['orderId', 'shopifyLineItemId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'product',
        constraint: 'product_shopId_shopifyProductId_key',
        columns: ['shopId', 'shopifyProductId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'review_request',
        constraint: 'review_request_token_key',
        columns: ['token'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'shop',
        constraint: 'shop_shopifyDomain_key',
        columns: ['shopifyDomain'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'shop',
        constraint: 'shop_shopifyShopId_key',
        columns: ['shopifyShopId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'shop_settings',
        constraint: 'shop_settings_shopId_key',
        columns: ['shopId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'shopify_session',
        constraint: 'shopify_session_sessionId_key',
        columns: ['sessionId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'user',
        constraint: 'user_shopId_email_key',
        columns: ['shopId', 'email'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'ai_summary',
        index: 'ai_summary_productId_idx_5858600a',
        columns: ['productId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'ai_summary',
        index: 'ai_summary_shopId_idx_e9207c6b',
        columns: ['shopId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'customer',
        index: 'customer_shopId_email_idx_79a3e451',
        columns: ['shopId', 'email'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'customer',
        index: 'customer_shopId_idx_e9207c6b',
        columns: ['shopId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'order',
        index: 'order_customerId_idx_b2a8a46c',
        columns: ['customerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'order',
        index: 'order_shopId_idx_e9207c6b',
        columns: ['shopId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'order_line_item',
        index: 'order_line_item_orderId_idx_d284871b',
        columns: ['orderId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'order_line_item',
        index: 'order_line_item_productId_idx_5858600a',
        columns: ['productId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'product',
        index: 'product_shopId_idx_e9207c6b',
        columns: ['shopId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'review',
        index: 'review_customerId_idx_b2a8a46c',
        columns: ['customerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'review',
        index: 'review_orderId_idx_d284871b',
        columns: ['orderId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'review',
        index: 'review_orderLineItemId_idx_559ef64d',
        columns: ['orderLineItemId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'review',
        index: 'review_productId_idx_5858600a',
        columns: ['productId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'review',
        index: 'review_shopId_idx_e9207c6b',
        columns: ['shopId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'review',
        index: 'review_shopId_status_idx_3e6d6af5',
        columns: ['shopId', 'status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'review_media',
        index: 'review_media_reviewId_idx_2f51da17',
        columns: ['reviewId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'review_reply',
        index: 'review_reply_reviewId_idx_2f51da17',
        columns: ['reviewId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'review_reply',
        index: 'review_reply_userId_idx_a489d58a',
        columns: ['userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'review_request',
        index: 'review_request_customerId_idx_b2a8a46c',
        columns: ['customerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'review_request',
        index: 'review_request_orderId_idx_d284871b',
        columns: ['orderId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'review_request',
        index: 'review_request_orderLineItemId_idx_559ef64d',
        columns: ['orderLineItemId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'review_request',
        index: 'review_request_productId_idx_5858600a',
        columns: ['productId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'review_request',
        index: 'review_request_shopId_idx_e9207c6b',
        columns: ['shopId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'review_request',
        index: 'review_request_shopId_status_idx_3e6d6af5',
        columns: ['shopId', 'status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'shopify_session',
        index: 'shopify_session_shopId_idx_e9207c6b',
        columns: ['shopId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'sync_job',
        index: 'sync_job_shopId_idx_e9207c6b',
        columns: ['shopId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'sync_job',
        index: 'sync_job_shopId_status_idx_3e6d6af5',
        columns: ['shopId', 'status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'sync_job',
        index: 'sync_job_type_idx_b6b604ea',
        columns: ['type'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'user',
        index: 'user_shopId_idx_e9207c6b',
        columns: ['shopId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'webhook_event',
        index: 'webhook_event_shopId_idx_e9207c6b',
        columns: ['shopId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'webhook_event',
        index: 'webhook_event_shopId_status_idx_3e6d6af5',
        columns: ['shopId', 'status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'webhook_event',
        index: 'webhook_event_topic_idx_655aa1bc',
        columns: ['topic'],
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'ai_summary',
        foreignKey: {
          name: 'ai_summary_shopId_fkey',
          columns: ['shopId'],
          references: { schema: 'public', table: 'shop', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'ai_summary',
        foreignKey: {
          name: 'ai_summary_productId_fkey',
          columns: ['productId'],
          references: { schema: 'public', table: 'product', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'customer',
        foreignKey: {
          name: 'customer_shopId_fkey',
          columns: ['shopId'],
          references: { schema: 'public', table: 'shop', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'order',
        foreignKey: {
          name: 'order_shopId_fkey',
          columns: ['shopId'],
          references: { schema: 'public', table: 'shop', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'order',
        foreignKey: {
          name: 'order_customerId_fkey',
          columns: ['customerId'],
          references: { schema: 'public', table: 'customer', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'order_line_item',
        foreignKey: {
          name: 'order_line_item_orderId_fkey',
          columns: ['orderId'],
          references: { schema: 'public', table: 'order', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'order_line_item',
        foreignKey: {
          name: 'order_line_item_productId_fkey',
          columns: ['productId'],
          references: { schema: 'public', table: 'product', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'product',
        foreignKey: {
          name: 'product_shopId_fkey',
          columns: ['shopId'],
          references: { schema: 'public', table: 'shop', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'review',
        foreignKey: {
          name: 'review_shopId_fkey',
          columns: ['shopId'],
          references: { schema: 'public', table: 'shop', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'review',
        foreignKey: {
          name: 'review_productId_fkey',
          columns: ['productId'],
          references: { schema: 'public', table: 'product', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'review',
        foreignKey: {
          name: 'review_customerId_fkey',
          columns: ['customerId'],
          references: { schema: 'public', table: 'customer', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'review',
        foreignKey: {
          name: 'review_orderId_fkey',
          columns: ['orderId'],
          references: { schema: 'public', table: 'order', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'review',
        foreignKey: {
          name: 'review_orderLineItemId_fkey',
          columns: ['orderLineItemId'],
          references: { schema: 'public', table: 'order_line_item', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'review_media',
        foreignKey: {
          name: 'review_media_reviewId_fkey',
          columns: ['reviewId'],
          references: { schema: 'public', table: 'review', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'review_reply',
        foreignKey: {
          name: 'review_reply_reviewId_fkey',
          columns: ['reviewId'],
          references: { schema: 'public', table: 'review', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'review_reply',
        foreignKey: {
          name: 'review_reply_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'review_request',
        foreignKey: {
          name: 'review_request_shopId_fkey',
          columns: ['shopId'],
          references: { schema: 'public', table: 'shop', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'review_request',
        foreignKey: {
          name: 'review_request_orderId_fkey',
          columns: ['orderId'],
          references: { schema: 'public', table: 'order', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'review_request',
        foreignKey: {
          name: 'review_request_orderLineItemId_fkey',
          columns: ['orderLineItemId'],
          references: { schema: 'public', table: 'order_line_item', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'review_request',
        foreignKey: {
          name: 'review_request_customerId_fkey',
          columns: ['customerId'],
          references: { schema: 'public', table: 'customer', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'review_request',
        foreignKey: {
          name: 'review_request_productId_fkey',
          columns: ['productId'],
          references: { schema: 'public', table: 'product', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'shop_settings',
        foreignKey: {
          name: 'shop_settings_shopId_fkey',
          columns: ['shopId'],
          references: { schema: 'public', table: 'shop', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'shopify_session',
        foreignKey: {
          name: 'shopify_session_shopId_fkey',
          columns: ['shopId'],
          references: { schema: 'public', table: 'shop', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'sync_job',
        foreignKey: {
          name: 'sync_job_shopId_fkey',
          columns: ['shopId'],
          references: { schema: 'public', table: 'shop', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'user',
        foreignKey: {
          name: 'user_shopId_fkey',
          columns: ['shopId'],
          references: { schema: 'public', table: 'shop', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'webhook_event',
        foreignKey: {
          name: 'webhook_event_shopId_fkey',
          columns: ['shopId'],
          references: { schema: 'public', table: 'shop', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
    ];
  }
}

MigrationCLI.run(import.meta.url, M);
